### ISSUE TITLE
Set default export results to all items

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#11]
We need to differentiate two situations in the results-JSON:

(A) An indicator with checkboxes has been shown, but all have NOT been checked. E.g.: A preregistration is present `"P_Preregistration": "Yes"`, but in `P_Preregistration_Content` nothing was was checked.
(B) An indicator with checkboxes was hidden due to a filter condition. E.g.: For meta-analyses, `P_Preregistration_Content` is hidden.

## Current state
Currently, the results-JSON looks identical: All items from `P_Preregistration_Content` are missing.

## Desired state:

- In (A), all checkbox items should be present in the results-JSON, with "false" as value
- In (B), all checkbox items should be present in the results-JSON, with "NA" as value.

That means, generally all checkbox items should be present in the results, and either have `true`, `false`, or `NA`.

**Comment by alpkaanaksu** [comment]
Done. adcc81958a7adc8b1a0373a37cf8ad8009256e38
