### ISSUE TITLE
mode=print: add filter as option

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#16]
Print mode, but only select indicators.

For example, show all open data indicators from publications:

https://nicebread.github.io/RESQUE/web/?mode=print&filter=P_OpenData

**Comment by nicebread** [comment]
Ideally, we can show arbitrary version of the packs. We should store old versions as separate files (e.g., in a subfolders of `packs`), and the display/printing mode has a dropdown box which lists all available versions. Then users can select the desired version and display it.
(See my email from 2024-08-08). We need version 0.3 (see releases/tags) as printed PDF for a BSc thesis.

**Comment by alpkaanaksu** [comment]
https://resque-framework.github.io/collector-app/preview

There is a dropdown to choose packs and a text field for filter. The filter works exactly the same as before. The top bar for input is hidden when printing.

<img width="1470" alt="Screenshot 2024-08-25 at 16 20 42" src="https://github.com/user-attachments/assets/05ea4de7-cbb6-40d6-99e1-b0f44e05d755">

[RESQUE Collector - Preview.pdf](https://github.com/user-attachments/files/16740616/RESQUE.Collector.-.Preview.pdf)

**Comment by nicebread** [comment]
Great!

(A) Can you add the option to show the indicator labels as a checkbox? (Otherwise user do not know what to put into the filter box). Also write an info to the filter box that it filters the indicator labels.

(B)
Can you add the capability to select the item from the dropdown box also via URL query strings?
Such as: 
`https://resque-framework.github.io/collector-app/preview?type=pubs&version=0.3.1&filter=P_Data&showmeta=true`

(this needs to be intelligently resolved to the underlying pack file).

I need this feature to include the printing into the RESQUE main website. E.g., when I write a section on the new theory indicators, I want to show them on the website.

**Comment by alpkaanaksu** [comment]
(A) is complete.

(B)
Now it works with `type`, `version`, `filter` and `showLabels`, you can try the link: https://resque-framework.github.io/collector-app/preview?type=pubs&version=0.3.1&filter=P_Data

I made it in a way that the selection menu disappears if we use query params (for embedding to the website?)

What does `showmeta` do?

**Comment by nicebread** [comment]
Great - this works already nicely on the website: 

<img width="1172" alt="image" src="https://github.com/user-attachments/assets/a1baca17-7281-444a-b83b-859fca974d85">

**Comment by nicebread** [comment]
> What does showmeta do?

The same as the "Show indicator labels" checkbox does - show or hide the labels. Maybe we should call it `show_labels`.

Can you furthermore add this JS snippet to the preview:

```
<script>
  function sendHeight() {
    const height = document.documentElement.scrollHeight;
    window.parent.postMessage(height, '*');
  }

  window.onload = sendHeight;
  window.onresize = sendHeight;
</script>
```

This helps resizing the iFrame on the website.

**Comment by alpkaanaksu** [comment]
> The same as the "Show indicator labels" checkbox does - show or hide the labels. Maybe we should call it show_labels.

We already have `showLabels`: https://resque-framework.github.io/collector-app/preview?type=pubs&version=0.3.1&filter=P_Data&showLabels=true

**Comment by alpkaanaksu** [comment]
I also copied your helper function

**Comment by nicebread** [comment]
Great! Can you add the preview options to the documentation?
I think then we can close the issue.
