### ISSUE TITLE
Radio button lists are mixed

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#24]
ich sehe gerade, dass es noch den einen Bug gibt, wo radio button Listen „gemischt“ sind: Ich glaube, immer wenn eine Radio list als Filter eine weitere radio list aufklappt:

![image](https://github.com/user-attachments/assets/d43c9d3f-8f7c-4024-85d2-8a123f91a7f3)

**Comment by alpkaanaksu** [comment]
Fixed. 69234ab23bd50d2a4d3895a12a06b20c3291511f
