### ISSUE TITLE
preview mode: Show expansion packs

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#25]
I added some expansion packs to `/packs`. Can they be listed in the dropdown box and display as preview?

**Comment by alpkaanaksu** [comment]
Done. 1f9617d38839994b41edb9af5325652ea5354022

<img width="298" alt="Screenshot 2024-08-29 at 16 56 20" src="https://github.com/user-attachments/assets/5ca8bdf9-4f44-405b-9ac2-3a8ab4d78bb7">
