### ISSUE TITLE
List of publications in tabs gets mixed up

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#28]
See attached json:

I started with an existing JSON that has 10 different publications.
After editing some of them, one publication is now present three times:

- Search for the title: `"Title": "Replicability, Robustness, and Reproducibility in Psychological Science"`
- This is present 3 times
- But the other indicators seem to be from the old publication

Maybe only the metadata (doi, title, etc) is overwritten for some reason?

[resque_schönbrodt_1726124754422.json](https://github.com/user-attachments/files/16974907/resque_schonbrodt_1726124754422.json)

**Comment by alpkaanaksu** [comment]
I think this should be fixed now f0b693fb4c560e21b0166ae0169aceae908091f5

> Maybe only the metadata (doi, title, etc) is overwritten for some reason?

This is what was happening. For me, it only happened after reloading the website after I imported the JSON file.

We have some 'effects' that are called after changes in the data. Our metadata fetching function was dependent on another one (`currentInput` is updated somewhere else, but we were using it for fetching the metadata), now the function for metadata is self-reliant, it only uses the `currentTab` variable.
