### ISSUE TITLE
Data is not properly saved in file

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#29]
Reproduce the bug:

- "Clear" --> "Clear all data"
- Add a publication. 
- In "Publication type (check all that apply)" (`P_TypeMethod`)
- Save to file ...

In fact, all checkboxes are not saved ...

Maybe introduced in 867aa4e8?

**Comment by alpkaanaksu** [comment]
Fixed. 38c8237bf49412a484da4647282541d1adf36d77

**Comment by nicebread** [comment]
Generally it works now, but not if the checklist is shown after a filter:

<img width="729" alt="image" src="https://github.com/user-attachments/assets/69472833-98cf-473f-be54-1aff6887dbf1">

Here the second checkbox group `P_Data_TypeBehavioral` is not saved.
