### ISSUE TITLE
Allow unlimited entries, allow deletion of entries

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#5]
From a user's point of view, it might be better to have one database of entered articles, and then you select those 10 that you want to submit to a hiring committee (and for the next hiring committee, you make a different selection).

That means, we would need to have two selections:

- include in best 10
- include in best 3

Furthermore, it should be possible to **delete** entries.

**Comment by alpkaanaksu** [comment]
How are you using the 'best papers' in the analyses?

What happens if I say that the paper is one of my best, but the score is subjectively one of the worst? Especially if we allow unlimited research outputs, what would be the difference to ranking the later?

**Comment by nicebread** [comment]
The remove button works and looks great!

But we still need two types of selections: best (say) 10 and best 3 (with stars).
The background is the following:

Applicants often apply to multiple professorship positions at the same time. Assume that they are only allowed to submit 10 research outputs for each application process: They might want to submit 10 (slightly) different papers to each hiring committee. It is more convenient to enter all of your papers into the app, and then select 10 different papers for each committee.

Maybe we use the existing stars for the "3 best papers", and put the "best 10" into the export function:
You maintain your local database of, say, 18 papers. And in export, you can select only 10 of these, export a JSON, and send that to the hiring committee.
