### ISSUE TITLE
Bug with cycling publication

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#7]
(see video from email).

Reproduce: As soon as one selects a second entry in the publication list in the left sidebar.

**Comment by alpkaanaksu** [comment]
This is a problem with how we handle DOI API calls

**Comment by alpkaanaksu** [comment]
I think #28 was also related to this, it was another case of the same problem, which was fixed for 'normal' situations. I believe the problem is fixed for both cases now.
